[UPDATE, ADD] Update to 1.7.5 - pretify the code and add function for update with file VERSION_

diff --git a/cpu-util b/cpu-util
--- a/cpu-util
+++ b/cpu-util
@@ -1,12 +1,35 @@
 #!/bin/bash
 
-VERSION=1.7.4
+##############################################################################
+#   /$$$$$$                                          /$$   /$$   /$$     /$$ /$$
+#  /$$__  $$                                        | $$  | $$  | $$    |__/| $$
+# | $$  \__/  /$$$$$$  /$$   /$$                    | $$  | $$ /$$$$$$   /$$| $$
+# | $$       /$$__  $$| $$  | $$       /$$$$$$      | $$  | $$|_  $$_/  | $$| $$
+# | $$      | $$  \ $$| $$  | $$      |______/      | $$  | $$  | $$    | $$| $$
+# | $$    $$| $$  | $$| $$  | $$                    | $$  | $$  | $$ /$$| $$| $$
+# |  $$$$$$/| $$$$$$$/|  $$$$$$/                    |  $$$$$$/  |  $$$$/| $$| $$
+#  \______/ | $$____/  \______/                      \______/    \___/  |__/|__/
+#           | $$                                                                
+#           | $$        created by berrabe                                                        
+#           |__/        https://github.com/berrabe/cpu-util                                                       
+##############################################################################
+
+# =========================================================== Check
+VERSION=1.7.5
 
 if [ "$EUID" -ne 0 ]
 	then
 		echo -ne "\n[!] please run as root\n"
-	exit
+		exit
 fi
+
+if [[ $# -eq 0 ]]
+	then
+		echo -ne "\n[?] type -h / --help for usage\n"
+		exit
+fi
+
+# =========================================================== Global Var
 
 # Color
 NOCOLOR='\033[0m'
@@ -23,51 +46,48 @@ kernel=$(hostnamectl | grep "Kernel" | cut -b 21-)
 os=$(hostnamectl | grep "Operating System" | cut -b 21-)
 arch=$(hostnamectl | grep "Architecture" | cut -b 21-)
 
-
 cols=$(tput cols)
 rows=$(tput lines)
 
-if [[ $# -eq 0 ]]
-	then
-		echo -ne "\n[?] type -h / --help for usage\n"
+# =========================================================== Func
 
-elif [[ $1 == "-h" || $1 == "--help" ]]
-	then
-		clear
-		echo -e "\t   == CPU Utillity =="
+function help_page() {
+	clear
+	echo -e "\t   == CPU Utillity =="
 
-		echo -ne " \n--------------------------------------- "
-		echo -ne " \n                         | Avail Mode |"
-		echo -e  " \n                         --------------\n"
+	echo -ne " \n--------------------------------------- "
+	echo -ne " \n                         | Avail Mode |"
+	echo -e  " \n                         --------------\n"
 
-		echo -e " [1] Monitoring \t[ -mo ]"
-		echo -e " [2] Set Max Frequency \t[ -sf ]"
-		echo -e " [3] Core Manager \t[ -cm ]"
+	echo -e " [1] Monitoring \t[ -mo ]"
+	echo -e " [2] Set Max Frequency \t[ -sf ]"
+	echo -e " [3] Core Manager \t[ -cm ]"
 
-		echo -ne " \n--------------------------------------- "
-		echo -ne " \n                             | Detail |"
-		echo -e  " \n                             ----------\n"
+	echo -ne " \n--------------------------------------- "
+	echo -ne " \n                             | Detail |"
+	echo -e  " \n                             ----------\n"
 
-		echo -e "-mo / --monitoring \n\twatch system usage every 1 sec\n"
-		echo -e "-sf / --set-freq [ freq in MHz | show ]\n\tset MAX freq for all CPU cores\n"
-		echo -e "-cm / --core-manager [ 0/1 | show ]\n\tturn on/off half of CPU cores\n"
-		echo -e "-h / --help \n\tshow help page"
-		echo -e "-v / --version \n\tprint script version"
+	echo -e "-mo / --monitoring \n\twatch system usage every 1 sec\n"
+	echo -e "-sf / --set-freq [ freq in MHz | show ]\n\tset MAX freq for all CPU cores\n"
+	echo -e "-cm / --core-manager [ 0/1 | show ]\n\tturn on/off half of CPU cores\n"
+	echo -e "-cu / --check-update \n\tcheck update from github"
+	echo -e "-h / --help \n\tshow help page"
+	echo -e "-v / --version \n\tprint script version"
 
-		echo -ne " \n--------------------------------------- "
-		echo -ne " \n                            | Example |"
-		echo -e  " \n                            -----------\n"
+	echo -ne " \n--------------------------------------- "
+	echo -ne " \n                            | Example |"
+	echo -e  " \n                            -----------\n"
 
-		echo -e ">> sudo cpu-util -mo"
-		echo -e ">> sudo cpu-util -sf 1000000"
-		echo -e ">> sudo cpu-util -sf show"
-		echo -e ">> sudo cpu-util -cm 0"
-		echo -e ">> sudo cpu-util -cm show"
+	echo -e ">> sudo cpu-util -mo"
+	echo -e ">> sudo cpu-util -sf 1000000"
+	echo -e ">> sudo cpu-util -sf show"
+	echo -e ">> sudo cpu-util -cm 0"
+	echo -e ">> sudo cpu-util -cm show"
+}
 
 
-elif [[ $1 == "-mo" || $1 == "--monitoring" ]]
-  then
-  	clear
+function monitoring() {
+	clear
     while true
 		do
 			if [[ $(tput cols) -ne $cols || $(tput lines) -ne $rows ]]
@@ -107,89 +127,143 @@ elif [[ $1 == "-mo" || $1 == "--monitoring" ]]
 	    tput cup 0 0
 	    sleep 1
 	done
-	# [+] Temp \t$(echo $temp | sed 's/-/\n\t\t/g') $(echo $cpu | sed -z 's/-/\n\t\t/g')
+# [+] Temp \t$(echo $temp | sed 's/-/\n\t\t/g') $(echo $cpu | sed -z 's/-/\n\t\t/g')
+
+}
 
 
-elif [[ $1 == "-sf" || $1 == "--set-freq" ]]
-	then
-		clear
+function set_freq() {
+	clear
 
-		if ! [[ $2 =~ ^[0-9]+$ || $2 == "show" ]]
-			then
-				echo -ne "\n[!] ERROR | argument not valid '$2'\n"
-				exit
-		fi
+	if ! [[ $1 =~ ^[0-9]+$ || $1 == "show" ]]
+		then
+			echo -ne "\n[!] ERROR | argument not valid '$1'\n"
+			exit
+	fi
 
-		if [[ $2 =~ "show" ]]
-			then
-				clear
+	if [[ $1 =~ "show" ]]
+		then
+			clear
 
-				for i in $(seq 0 $core_)
-					do
-						buffer_info=$(cat "/sys/devices/system/cpu/cpu$i/cpufreq/cpuinfo_max_freq" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
-						buffer_scaling=$(cat "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
-
-						echo -en "Scaling Freq Core $i \t=> $buffer_scaling / $buffer_info MHz\n"	
-				done
-		else
 			for i in $(seq 0 $core_)
 				do
-					# echo -ne "Core $i \t=> " && echo -ne $2 | sudo tee "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq" && echo " MHz"
-					file="/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq"
-					su -c "echo $2 > '$file'"
+					buffer_info=$(cat "/sys/devices/system/cpu/cpu$i/cpufreq/cpuinfo_max_freq" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
+					buffer_scaling=$(cat "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
 
-					echo -e "Core $i \t=> $(echo $2 | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta') MHz"
-				done
-		fi
+					echo -en "Scaling Freq Core $i \t=> $buffer_scaling / $buffer_info MHz\n"	
+			done
+	else
+		for i in $(seq 0 $core_)
+			do
+				# echo -ne "Core $i \t=> " && echo -ne $2 | sudo tee "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq" && echo " MHz"
+				file="/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq"
+				su -c "echo $1 > '$file'"
+
+				echo -e "Core $i \t=> $(echo $1 | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta') MHz"
+			done
+	fi
+}
 
 
-elif [[ $1 == "-cm" || $1 == "--core-manager" ]]
-	then
-		clear
+function core_manage() {
+	clear
 
-		if ! [[ $2 =~ ^[0-9]+$ || $2 == "show" ]]
-			then
-				echo -ne "\n[!] ERROR | argument not valid '$2'\n"
-				exit
-		fi
+	if ! [[ $1 =~ ^[0-9]+$ || $1 == "show" ]]
+		then
+			echo -ne "\n[!] ERROR | argument not valid '$1'\n"
+			exit
+	fi
 
-		_cores="$(($s_cores/2))"
-		cores_="$(($s_cores-1))"
+	_cores="$(($s_cores/2))"
+	cores_="$(($s_cores-1))"
 
-		if [[ $2 =~ "show" ]]
-			then
-				echo  -e "Core 0 > [always ON]"
-				for i in $(seq 1 $cores_)
-					do				
-						file="/sys/devices/system/cpu/cpu$i/online"
-						value=$(cat $file)
-
-						echo  -e "Core $i > $([[ $value = 1 ]] && echo "ON" || echo "Off") "
-					done
-		else
-			for i in $(seq $_cores $cores_)
-				do
+	if [[ $1 =~ "show" ]]
+		then
+			echo  -e "Core 0 > [always ON]"
+			for i in $(seq 1 $cores_)
+				do				
 					file="/sys/devices/system/cpu/cpu$i/online"
-					su -c "echo $2 > '$file'"
+					value=$(cat $file)
 
-					echo  -e "Core $i > $2 $([[ $2 = 1 ]] && echo "[ON]" || echo "[Off]") "
+					echo  -e "Core $i > $([[ $value = 1 ]] && echo "ON" || echo "Off") "
 				done
-		fi
+	else
+		for i in $(seq $_cores $cores_)
+			do
+				file="/sys/devices/system/cpu/cpu$i/online"
+				su -c "echo $1 > '$file'"
+
+				echo  -e "Core $i > $1 $([[ $1 = 1 ]] && echo "[ON]" || echo "[Off]") "
+			done
+	fi
+}
 
 
-elif [[ $1 == "-v" || $1 == "--version" ]]
-	then
-		clear
-		echo -e "\t   == CPU Utillity =="
-		echo -ne "\n[+] Ver $VERSION"
-		echo -ne "\n[+] by berrabe"
+function show_ver() {
+	clear
+	echo -e "\t   == CPU Utillity =="
+	echo -ne "\n[+] Ver $VERSION"
+	echo -ne "\n[+] by berrabe"
 
-		echo -e "\n\n[!] Keep It Simple"
+	echo -e "\n\n[!] Keep It Simple"
+}
 
 
-else
-	echo -e "\n[!] ERROR | Mode Not Found"
+function check_update() {
+	clear
+	echo -e "[+] Checking Update ...."
 
-fi
+	fetched=$(wget -qO- https://raw.githubusercontent.com/berrabe/cpu-util/master/VERSION_ | cut -b 9-13)
+	p_ver=$(echo $fetched | sed 's/\.//g' )
+	l_ver=$(echo $VERSION | sed 's/\.//g' )
 
+	if [[  $(echo $fetched | wc -c) -gt 5 ]]
+		then
+			if [[ $l_ver -ge $p_ver ]]
+				then
+					echo -e "\n[!] Up To Date :))"
+					echo -e "[!] V$VERSION"
+			else
+					echo -e "\n[!] Update Availabla \t=> $fetched"
+					echo -e "[!] Current Version \t=> $VERSION"
+					# echo -e "[!] Public Version \t=> $link"
+					echo -e "\n[+] Download on https://github.com/berrabe/cpu-util"
+			fi
+	else
+		echo -e "\n[+] ERROR"
+	fi
+}
+
+# =========================================================== Logic
+
+
+case $1 in
+	"-mo" | "--monitoring")
+		monitoring
+		;;
+
+	"-sf" | "--set-freq")
+		set_freq $2
+		;;
+
+	"-cm" | "--core-manager")
+		core_manage $2
+		;;
+
+	"-v" | "--version")
+		show_ver
+		;;
+
+	"-h" | "--help")
+		help_page
+		;;
+
+	"-cu" | "--check-update")
+		check_update
+		;;
+
+	*)
+		echo -e "\n[!] ERROR | Arg Not Found"
+		;;
+esac
 
